---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ddbcms
  name: ddbcms-database
spec:
  selector:
      matchLabels:
        app: ddbcms-database
  template:
      metadata:
        labels:
          app: ddbcms-database
          tier: backend
      spec:
        containers:
        - name: ding2-mysql
          image: ding2/ding2-mysql
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'password'
          - name: MYSQL_USER
            value: 'db'
          - name: MYSQL_PASSWORD
            value: 'db'
          - name: MYSQL_DATABASE
            value: 'db'
          ports:
          - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddbcms
  name: ddbcms-database
  labels:
    tier: backend
spec:
  selector:
    app: ddbcms-database
  ports:
  - protocol: TCP
    port: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  namespace: ddbcms
  name: ddbcms-database-sql
  labels:
    tier: backend
spec:
  selector:
    app: ddbcms-database
  ports:
  - protocol: TCP
    port: 3306
  type: NodePort